Repository yiisoft/yii-debug, pull requests merged in 2020-12, with the labels that each got.

#76 Fix error when logging non-strings
  src/Collector/LogCollector.php
  src/Collector/LogCollectorInterface.php
  tests/Collector/WebAppInfoCollectorTest.php
Labels: status:code review, type:bug

#78 Ignore /assets/* routes
  config/params.php
Labels: status:code review

#79 Add Storage read support
  composer.json
  src/Collector/CollectorTrait.php
  src/Collector/EventCollector.php
  src/Collector/RequestCollector.php
  src/Collector/RouterCollector.php
  src/Collector/WebAppInfoCollector.php
  src/Debugger.php
  src/DebuggerIdGenerator.php
  src/FlattenException.php
  src/Proxy/ContainerInterfaceProxy.php
  src/Proxy/ContainerProxyConfig.php
  src/Proxy/ProxyLogTrait.php
  src/ProxyServiceProvider.php
  src/Storage/FileStorage.php
  src/Storage/MemoryStorage.php
  src/Storage/StorageInterface.php
  tests/Storage/AbstractStorageTest.php
  tests/Storage/MemoryStorageTest.php
Labels: status:code review

#80 Cleanup FlattenException
  src/FlattenException.php
Labels: status:code review

#77 Reindex objects
  src/Storage/FileStorage.php
Labels: status:under development
