Repository yiisoft/yii-debug, pull requests merged in 2022-07, with the labels that each got.

#128 Sync the latest changes with proxy
  src/Proxy/ServiceMethodProxy.php
  src/Proxy/ServiceProxy.php
Labels: type:task

#127 Add `yiisoft/view` `^5.0` version support
  composer.json
Labels: type:enhancement, status:under development, dependencies

#133 Some refactoring
  config/common.php
  config/params.php
  src/Collector/AssetCollector.php
  src/Collector/AssetLoaderInterfaceProxy.php
  src/Collector/CommandCollector.php
  src/Collector/ConsoleAppInfoCollector.php
  src/Collector/ContainerInterfaceProxy.php
  src/Collector/ContainerProxyConfig.php
  src/Collector/EventCollector.php
  src/Collector/EventCollectorInterface.php
  src/Collector/EventDispatcherInterfaceProxy.php
  src/Collector/LogCollector.php
  src/Collector/LogCollectorInterface.php
  src/Collector/LoggerInterfaceProxy.php
  src/Collector/MiddlewareCollector.php
  src/Collector/ProxyLogTrait.php
  src/Collector/RequestCollector.php
  src/Collector/RouterCollector.php
  src/Collector/RouterCollectorInterface.php
  src/Collector/ServiceCollector.php
  src/Collector/ServiceCollectorInterface.php
  src/Collector/ServiceMethodProxy.php
  src/Collector/ServiceProxy.php
  src/Collector/UrlMatcherInterfaceProxy.php
  src/Collector/WebAppInfoCollector.php
  src/DebugServiceProvider.php
  src/ProxyServiceProvider.php
  tests/Collector/CommandCollectorTest.php
  tests/Collector/ContainerInterfaceProxyTest.php
  tests/Collector/ContainerProxyConfigTest.php
  tests/Collector/EventDispatcherProxyTest.php
  tests/Collector/LoggerProxyTest.php
  tests/Collector/RequestCollectorTest.php
  tests/Collector/ServiceCollectorTest.php
  tests/Collector/ServiceProxyTest.php
  tests/Collector/UrlMatcherInterfaceProxyTest.php
  tests/DebugServiceProviderTest.php
  tests/Proxy/ServiceProxyTest.php
  tests/ProxyServiceProviderTest.php
Labels: status:code review

#132 Add ValidatorCollector
  composer.json
  config/params.php
  src/Collector/ValidatorCollector.php
  src/Collector/ValidatorInterfaceProxy.php
  tests/Collector/ValidatorCollectorTest.php
Labels: status:code review

#139 Add `yiisoft/view` version `^6.0` support
  composer.json
Labels: status:code review

#142 Fix validator collector
  src/Collector/ValidatorCollector.php
  src/Collector/ValidatorInterfaceProxy.php
  tests/Collector/ValidatorCollectorTest.php
Labels: status:code review

#143 Remove cache dependency
  composer.json
Labels: status:code review

#144 Add ignore commands
  config/console.php
  config/events-console.php
  config/params.php
  config/web.php
  src/Collector/CommandCollector.php
  src/Collector/ConsoleAppInfoCollector.php
  src/Debugger.php
  tests/Collector/ConsoleAppInfoCollectorTest.php
  tests/DebuggerTest.php
Labels: status:code review

#140 Add queue collector
  composer.json
  config/params.php
  src/Collector/QueueCollector.php
  src/Collector/QueueDecorator.php
  src/Collector/QueueFactoryInterfaceProxy.php
  src/Collector/QueueWorkerInterfaceProxy.php
  tests/Collector/QueueCollectorTest.php
  tests/Collector/QueueDecoratorTest.php
  tests/Support/DummyQueue.php
Labels: status:code review
